# Generated by Django 4.2.2 on 2023-06-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Translation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_text", models.TextField()),
                ("source_lang", models.CharField(max_length=10)),
                ("target_lang", models.CharField(max_length=10)),
                ("translated_text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"verbose_name_plural": "Translation",},
        ),
    ]
